- hosts: localhost
  connection: local
  roles:
    - { role: homebrew, tags: [homebrew] }
    - { role: zsh, tags: [zsh], become: yes }
    - { role: dotfiles, tags: [dotfiles]}
    - { role: jekyll, tags: [jekyll] }
